[package]
name = "eth_user_integrity"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "eth_user_integrity"

[dependencies]
hdi = { workspace = true }

serde = { workspace = true }
eth_user_integrity = { path = "../../integrity/eth_user" }
